#!/usr/bin/env python3
"""Generate SQL for bot accounts + characters, and the matching "bots" list
for config.json.

    python create_bots.py --count 20 --out bots.sql --config-out bots.json
    mysql -u ragnarok -p ragnarok < bots.sql

Bots use a dedicated account id range (default 3000000+) so they never
collide with real players. Each account gets a long random password; nobody
needs to log in to them with a client.
"""

import argparse
import json
import random
import secrets

FIRST = ["Mew", "Ploy", "Bank", "Beam", "Nut", "Pond", "Fern", "Ice", "Gun", "Top", "Joy", "Kwan",
         "Film", "Mint", "Boss", "Tae", "Nam", "Pim", "Oat", "Arm", "Ohm", "Earth", "Tong", "Win",
         "Kaew", "Fah", "Namo", "Pang", "Bow", "Toon", "Cake", "Pupe", "Jah", "Tar", "View", "Jay"]
STYLE = ["{f}", "{f}{n}", "x{f}x", "{f}_{w}", "{w}{f}", "{f}za", "{f}{w}", "Nong{f}", "P{f}", "{f}{f2}"]
WORDS = ["Dark", "Moon", "Star", "Kitty", "King", "Luv", "Neko", "Shadow", "Angel", "Sky", "Ro", "Pro"]

# class id -> (weapon id, equip location mask)
JOBS = {
    0: (1201, 2),    # Novice   - Knife
    1: (1101, 2),    # Swordman - Sword
    2: (1601, 2),    # Mage     - Rod
    3: (1701, 34),   # Archer   - Bow (both hands)
    4: (1501, 2),    # Acolyte  - Club
    5: (1301, 2),    # Merchant - Axe
    6: (1201, 2),    # Thief    - Knife
}
ARMOR = (2301, 16)       # Cotton Shirt
ARROWS = (1750, 32768)   # Arrow
RED_POTION = 501


def status_points(level):
    points = 48
    for lv in range(1, level):
        points += lv // 5 + 3
    return points


def make_name(rng, used):
    for _ in range(1000):
        f = rng.choice(FIRST)
        name = rng.choice(STYLE).format(f=f, f2=rng.choice(FIRST), n=rng.randint(1, 99), w=rng.choice(WORDS))
        if 4 <= len(name) <= 23 and name.lower() not in used:
            used.add(name.lower())
            return name
    raise RuntimeError("could not generate a unique name")


def sql_str(value):
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--count", type=int, default=10)
    ap.add_argument("--start-account-id", type=int, default=3000000)
    ap.add_argument("--start-char-id", type=int, default=3000000)
    ap.add_argument("--min-level", type=int, default=1)
    ap.add_argument("--max-level", type=int, default=30)
    ap.add_argument("--jobs", default="1,2,3,4,5,6", help="comma separated class ids to pick from")
    ap.add_argument("--personalities", default="hardcore,merchant,chill")
    ap.add_argument("--map", default="prontera")
    ap.add_argument("--x", type=int, default=155)
    ap.add_argument("--y", type=int, default=187)
    ap.add_argument("--prefix", default="", help="fixed name prefix, e.g. LoadBot (names become LoadBot0001...)")
    ap.add_argument("--seed", type=int)
    ap.add_argument("--out", default="bots.sql")
    ap.add_argument("--config-out", default="bots.json")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    jobs = [int(j) for j in args.jobs.split(",")]
    personalities = args.personalities.split(",")
    used = set()
    sql = ["-- Generated by tools/aibot/create_bots.py", "START TRANSACTION;"]
    bots = []

    for i in range(args.count):
        aid = args.start_account_id + i
        cid = args.start_char_id + i
        name = "%s%04d" % (args.prefix, i + 1) if args.prefix else make_name(rng, used)
        sex = rng.choice("MF")
        job = rng.choice(jobs)
        blv = rng.randint(args.min_level, args.max_level)
        jlv = 1 if job == 0 else min(50, max(1, blv // 2 + rng.randint(0, 5)))
        skill_points = (jlv - 1) if job == 0 else 9 + (jlv - 1)
        weapon, wloc = JOBS.get(job, JOBS[0])
        personality = rng.choice(personalities)

        sql.append(
            "INSERT INTO `login` (`account_id`,`userid`,`user_pass`,`sex`,`email`,`group_id`,`character_slots`) VALUES "
            "(%d,%s,%s,'%s','aibot@localhost',0,1);" % (aid, sql_str("aibot_%d" % aid), sql_str(secrets.token_hex(12)), sex)
        )
        sql.append(
            "INSERT INTO `char` (`char_id`,`account_id`,`char_num`,`name`,`class`,`base_level`,`job_level`,"
            "`str`,`agi`,`vit`,`int`,`dex`,`luk`,`max_hp`,`hp`,`max_sp`,`sp`,`status_point`,`skill_point`,"
            "`zeny`,`hair`,`hair_color`,`last_map`,`last_x`,`last_y`,`save_map`,`save_x`,`save_y`,`sex`) VALUES "
            "(%d,%d,0,%s,%d,%d,%d,1,1,1,1,1,1,100,100,20,20,%d,%d,%d,%d,%d,%s,%d,%d,%s,%d,%d,'%s');"
            % (cid, aid, sql_str(name), job, blv, jlv, status_points(blv), skill_points,
               rng.randint(500, 5000) * max(1, blv // 5), rng.randint(1, 20), rng.randint(0, 8),
               sql_str(args.map), args.x, args.y, sql_str(args.map), args.x, args.y, sex)
        )
        items = [(weapon, 1, wloc), (ARMOR[0], 1, ARMOR[1]), (RED_POTION, 30, 0)]
        if job == 3:
            items.append((ARROWS[0], 1000, ARROWS[1]))
        for nameid, amount, equip in items:
            sql.append(
                "INSERT INTO `inventory` (`char_id`,`nameid`,`amount`,`equip`,`identify`) VALUES (%d,%d,%d,%d,1);"
                % (cid, nameid, amount, equip)
            )
        bots.append({"name": name, "personality": personality})

    sql.append("COMMIT;")
    with open(args.out, "w", encoding="utf-8") as fp:
        fp.write("\n".join(sql) + "\n")
    with open(args.config_out, "w", encoding="utf-8") as fp:
        json.dump({"bots": bots}, fp, ensure_ascii=False, indent=2)

    print("wrote %s (%d bots) and %s" % (args.out, args.count, args.config_out))
    print("remove them later with:")
    print("  DELETE FROM `inventory` WHERE `char_id` BETWEEN %d AND %d;" % (args.start_char_id, args.start_char_id + args.count - 1))
    print("  DELETE FROM `char` WHERE `char_id` BETWEEN %d AND %d;" % (args.start_char_id, args.start_char_id + args.count - 1))
    print("  DELETE FROM `login` WHERE `account_id` BETWEEN %d AND %d;" % (args.start_account_id, args.start_account_id + args.count - 1))


if __name__ == "__main__":
    main()
