<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RO_Manager</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net45</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <NoWarn>$(NoWarn);CS0168;CS0219;CS0414;CS0649;CS0169;CS8981</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="ROManager.bg.jpg" />
    <EmbeddedResource Include="ROManager.bg.jpg" LogicalName="ROManager.bg.jpg" WithCulture="false" Type="Non-Resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Data" />
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>
